name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and run with Docker Compose
        run: |
          docker compose stop
          docker compose build --no-cache
          docker compose up -d
        env:
          API_HOST: ${{ secrets.API_HOST }}